name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install
        pip install poetry
        cd tiny-database && poetry install --no-root
        cd ..
    - name: Run pre-commit
      run: pre-commit run --all-files
